version: '3.7'
services:
    website:
        image: ${CI_REGISTRY}/bumblebee/website:latest
        environment:
            - NODE_ENV=development
            - ANGULAR_ENV=prod
            - USE_NODEMON=false
            - NPM_INSTALL_AFTER=false
            - NG_OPTIONAL=--prod
        depends_on:
            - api
        networks:
            - proxy-net
        deploy:
            labels:
                - traefik.enable=true
                - traefik.http.routers.bmbl-web.rule=Host(`bmbl.cloud`) || Host(`bmbl.mijnproject.nu`)
                - traefik.http.routers.bmbl-web.tls=true
                - traefik.http.routers.bmbl-web.tls.certresolver=myresolver
                - traefik.http.services.bmbl-web-service.loadbalancer.server.port=80
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s

networks:
   proxy-net:
      external: true